# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editor.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog_Editor(object):
    def setupUi(self, Dialog_Editor):
        Dialog_Editor.setObjectName(_fromUtf8("Dialog_Editor"))
        Dialog_Editor.resize(1114, 797)
        self.tabWidget = QtGui.QTabWidget(Dialog_Editor)
        self.tabWidget.setGeometry(QtCore.QRect(0, 170, 1111, 626))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.Button_AddPic = QtGui.QToolButton(self.tab)
        self.Button_AddPic.setGeometry(QtCore.QRect(565, 0, 56, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_AddPic.setFont(font)
        self.Button_AddPic.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_AddPic.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/r_icon/pic/r_icon/write_mail.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_AddPic.setIcon(icon)
        self.Button_AddPic.setIconSize(QtCore.QSize(48, 48))
        self.Button_AddPic.setCheckable(False)
        self.Button_AddPic.setChecked(False)
        self.Button_AddPic.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.Button_AddPic.setAutoRaise(True)
        self.Button_AddPic.setArrowType(QtCore.Qt.NoArrow)
        self.Button_AddPic.setObjectName(_fromUtf8("Button_AddPic"))
        self.line = QtGui.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(246, -5, 10, 56))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(363, 0, 11, 51))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.textEdit = QtGui.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(5, 55, 1096, 541))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.fontSizeBox = QtGui.QSpinBox(self.tab)
        self.fontSizeBox.setGeometry(QtCore.QRect(145, 10, 86, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fontSizeBox.setFont(font)
        self.fontSizeBox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.fontSizeBox.setMinimum(10)
        self.fontSizeBox.setMaximum(80)
        self.fontSizeBox.setProperty("value", 16)
        self.fontSizeBox.setObjectName(_fromUtf8("fontSizeBox"))
        self.Button_U = QtGui.QToolButton(self.tab)
        self.Button_U.setGeometry(QtCore.QRect(495, 0, 56, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_U.setFont(font)
        self.Button_U.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_U.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit_tool/pic/tools/textunder.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_U.setIcon(icon1)
        self.Button_U.setIconSize(QtCore.QSize(32, 32))
        self.Button_U.setCheckable(True)
        self.Button_U.setAutoRaise(True)
        self.Button_U.setObjectName(_fromUtf8("Button_U"))
        self.fontBox = QtGui.QFontComboBox(self.tab)
        self.fontBox.setGeometry(QtCore.QRect(10, 10, 116, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.fontBox.setFont(font)
        self.fontBox.setFocusPolicy(QtCore.Qt.ClickFocus)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("SimSun-ExtB"))
        font.setPointSize(9)
        self.fontBox.setCurrentFont(font)
        self.fontBox.setObjectName(_fromUtf8("fontBox"))
        self.Button_I = QtGui.QToolButton(self.tab)
        self.Button_I.setGeometry(QtCore.QRect(435, 0, 56, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_I.setFont(font)
        self.Button_I.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_I.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit_tool/pic/tools/textitalic.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_I.setIcon(icon2)
        self.Button_I.setIconSize(QtCore.QSize(32, 32))
        self.Button_I.setCheckable(True)
        self.Button_I.setAutoRaise(True)
        self.Button_I.setObjectName(_fromUtf8("Button_I"))
        self.Button_B = QtGui.QToolButton(self.tab)
        self.Button_B.setGeometry(QtCore.QRect(375, 0, 56, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_B.setFont(font)
        self.Button_B.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_B.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit_tool/pic/tools/textbold.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_B.setIcon(icon3)
        self.Button_B.setIconSize(QtCore.QSize(32, 32))
        self.Button_B.setCheckable(True)
        self.Button_B.setChecked(False)
        self.Button_B.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.Button_B.setAutoRaise(True)
        self.Button_B.setArrowType(QtCore.Qt.NoArrow)
        self.Button_B.setObjectName(_fromUtf8("Button_B"))
        self.line_3 = QtGui.QFrame(self.tab)
        self.line_3.setGeometry(QtCore.QRect(555, 0, 10, 51))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.PlainTextEdit_Html = QtGui.QPlainTextEdit(self.tab_2)
        self.PlainTextEdit_Html.setGeometry(QtCore.QRect(5, 5, 1096, 591))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PlainTextEdit_Html.setFont(font)
        self.PlainTextEdit_Html.setPlainText(_fromUtf8(""))
        self.PlainTextEdit_Html.setObjectName(_fromUtf8("PlainTextEdit_Html"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.lineEdit = QtGui.QLineEdit(Dialog_Editor)
        self.lineEdit.setGeometry(QtCore.QRect(75, 125, 1031, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit.setFont(font)
        self.lineEdit.setText(_fromUtf8(""))
        self.lineEdit.setFrame(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.label = QtGui.QLabel(Dialog_Editor)
        self.label.setGeometry(QtCore.QRect(10, 130, 61, 36))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("SimSun-ExtB"))
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.tabWidget.raise_()
        self.textEdit.raise_()
        self.Button_AddPic.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.textEdit.raise_()
        self.fontSizeBox.raise_()
        self.Button_U.raise_()
        self.fontBox.raise_()
        self.Button_B.raise_()
        self.Button_I.raise_()
        self.lineEdit.raise_()
        self.label.raise_()

        self.retranslateUi(Dialog_Editor)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Editor)

    def retranslateUi(self, Dialog_Editor):
        Dialog_Editor.setWindowTitle(_translate("Dialog_Editor", "Dialog", None))
        self.Button_AddPic.setToolTip(_translate("Dialog_Editor", "插入图片", None))
        self.textEdit.setHtml(_translate("Dialog_Editor", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.Button_U.setToolTip(_translate("Dialog_Editor", "下划线", None))
        self.Button_I.setToolTip(_translate("Dialog_Editor", "斜体", None))
        self.Button_B.setToolTip(_translate("Dialog_Editor", "粗体", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog_Editor", "编辑", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog_Editor", "html", None))
        self.label.setText(_translate("Dialog_Editor", "主题：", None))

import send1_rc
