#!/usr/bin/python
# -*- coding: utf-8 -*-


def test_aupt_import():

    import asynchat
    import glob
    import pdb

    import json
    import logging
    import tornado

    import abc
    import anydbm
    import shelve
    import asynchat
    import asyncore
    import base64
    import BaseHTTPServer

    import bdb
    import binhex
    import bisect
    import calendar
    import cgi
    import CGIHTTPServer
    import cgitb
    import chunk
    import cmd
    import code
    import codecs
    import codeop
    import collections
    import colorsys
    import commands
    import compileall
    import ConfigParser
    import contextlib
    import Cookie
    import cookielib
    import copy
    import copy_reg
    import csv
    import difflib
    import dircache
    import dis
    import DocXMLRPCServer
    import dumbdbm
    import dummy_thread
    import dummy_threading
    import filecmp
    import fileinput
    import fnmatch
    import formatter
    import ftplib
    import functools
    import getopt
    import getpass
    import gettext
    import glob
    import gzip
    import hashlib
    import heapq
    import hmac
    import htmlentitydefs
    import htmllib
    import HTMLParser
    import httplib
    import ihooks
    import imaplib
    import imghdr
    import imputil
    import io
    import keyword
    import linecache
    import locale
    import mailbox
    import mailcap
    import markupbase
    import hashlib
    import mhlib
    import mimetools
    import mimetypes
    import email
    import mutex
    import netrc
    import new
    import nntplib
    import ntpath
    import nturl2path
    import numbers
    import opcode
    import os
    import os2emxpath
    import pdb
    import pickle
    import pickletools
    import pipes
    import pkgutil
    import platform
    import plistlib
    import subprocess
    import poplib
    import posixpath
    import pprint
    import profile
    import pstats
    import pyclbr
    import Queue
    import quopri
    import random
    import re
    import repr
    import rexec
    import rfc822
    import robotparser
    import runpy
    import sched

    import sgmllib
    import shlex
    import shutil
    import SimpleHTTPServer
    import SimpleXMLRPCServer
    import site
    import smtpd
    import smtplib
    import socket
    import SocketServer
    import re
    import sre_compile
    import sre_constants
    import sre_parse
    import ssl
    import stat
    import statvfs
    import string
    import StringIO
    import stringold
    import stringprep
    import struct
    import subprocess
    import symbol
    import sysconfig
    import tabnanny
    import tarfile
    import telnetlib
    import tempfile
    import textwrap
    import this
    import threading
    import timeit
    import token
    import tokenize
    import trace
    import traceback
    import types
    import urllib
    import urllib2
    import urlparse
    import user
    import uu
    import uuid
    import warnings
    import webbrowser
    import whichdb
    import xdrlib
    import xml
    import xmlrpclib
    import zipfile
