#!/usr/bin/python
# -*- coding: utf-8 -*-

ERROR_SUCCESS = 0
ERROR_FINISH = 1
ERROR_PAUSE = 2   # 预留，未用
ERROR_OPEN_APPEND_FAILED = 3
ERROR_READ_APPEND_FAILED = 4
ERROR_SEND_TOO_MANY = 5
ERROR_SEND_TOO_MANY_NEED_WAIT = 6
ERROR_CONNECT_FAILED = 7
ERROR_LOGIN_FAILED = 8
ERROR_SEND_FAILED_UNKNOWN = 9
ERROR_SEND_FAILED_UNKNOWN_TOO_MANY = 10
ERROR_SOME_EMAILS_FAILED = 11
ERROR_OPEN_BODY_FAILED = 12
ERROR_READ_BODY_FAILED = 13
ERROR_DECODE_BODY_FAILED = 14

ERROR_OPEN_XLS_FAILED = 101
ERROR_READ_MATRIX_DB_FAILED = 102


