# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editor.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog_Editor(object):
    def setupUi(self, Dialog_Editor):
        Dialog_Editor.setObjectName(_fromUtf8("Dialog_Editor"))
        Dialog_Editor.resize(1190, 760)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/r_icon/pic/r_icon/write_mail.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog_Editor.setWindowIcon(icon)
        self.verticalLayout_3 = QtGui.QVBoxLayout(Dialog_Editor)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.Button_OK = QtGui.QPushButton(Dialog_Editor)
        self.Button_OK.setMinimumSize(QtCore.QSize(130, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Button_OK.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/r_icon/pic/r_icon/ok.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_OK.setIcon(icon1)
        self.Button_OK.setIconSize(QtCore.QSize(32, 32))
        self.Button_OK.setFlat(False)
        self.Button_OK.setObjectName(_fromUtf8("Button_OK"))
        self.horizontalLayout_4.addWidget(self.Button_OK)
        self.Button_Cancel = QtGui.QPushButton(Dialog_Editor)
        self.Button_Cancel.setMinimumSize(QtCore.QSize(130, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Button_Cancel.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/r_icon/pic/r_icon/cancel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_Cancel.setIcon(icon2)
        self.Button_Cancel.setIconSize(QtCore.QSize(32, 32))
        self.Button_Cancel.setAutoDefault(False)
        self.Button_Cancel.setFlat(False)
        self.Button_Cancel.setObjectName(_fromUtf8("Button_Cancel"))
        self.horizontalLayout_4.addWidget(self.Button_Cancel)
        self.Button_Save = QtGui.QPushButton(Dialog_Editor)
        self.Button_Save.setMinimumSize(QtCore.QSize(130, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Button_Save.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit_tool/pic/tools/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_Save.setIcon(icon3)
        self.Button_Save.setIconSize(QtCore.QSize(32, 32))
        self.Button_Save.setAutoDefault(False)
        self.Button_Save.setDefault(False)
        self.Button_Save.setFlat(False)
        self.Button_Save.setObjectName(_fromUtf8("Button_Save"))
        self.horizontalLayout_4.addWidget(self.Button_Save)
        self.Button_Appendix = QtGui.QPushButton(Dialog_Editor)
        self.Button_Appendix.setMinimumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Button_Appendix.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit_tool/pic/editor/attachment6.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_Appendix.setIcon(icon4)
        self.Button_Appendix.setIconSize(QtCore.QSize(32, 32))
        self.Button_Appendix.setAutoDefault(False)
        self.Button_Appendix.setFlat(False)
        self.Button_Appendix.setObjectName(_fromUtf8("Button_Appendix"))
        self.horizontalLayout_4.addWidget(self.Button_Appendix)
        spacerItem = QtGui.QSpacerItem(600, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label = QtGui.QLabel(Dialog_Editor)
        self.label.setMinimumSize(QtCore.QSize(0, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("SimSun-ExtB"))
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_5.addWidget(self.label)
        self.Edit_Sub = QtGui.QLineEdit(Dialog_Editor)
        self.Edit_Sub.setMinimumSize(QtCore.QSize(1101, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Edit_Sub.setFont(font)
        self.Edit_Sub.setText(_fromUtf8(""))
        self.Edit_Sub.setFrame(True)
        self.Edit_Sub.setObjectName(_fromUtf8("Edit_Sub"))
        self.horizontalLayout_5.addWidget(self.Edit_Sub)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.tabWidget = QtGui.QTabWidget(Dialog_Editor)
        self.tabWidget.setMinimumSize(QtCore.QSize(1172, 645))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_edit = QtGui.QWidget()
        self.tab_edit.setObjectName(_fromUtf8("tab_edit"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_edit)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.fontBox = QtGui.QFontComboBox(self.tab_edit)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fontBox.sizePolicy().hasHeightForWidth())
        self.fontBox.setSizePolicy(sizePolicy)
        self.fontBox.setMinimumSize(QtCore.QSize(140, 31))
        self.fontBox.setMaximumSize(QtCore.QSize(300, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.fontBox.setFont(font)
        self.fontBox.setFocusPolicy(QtCore.Qt.ClickFocus)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("SimSun-ExtB"))
        font.setPointSize(9)
        self.fontBox.setCurrentFont(font)
        self.fontBox.setObjectName(_fromUtf8("fontBox"))
        self.horizontalLayout.addWidget(self.fontBox)
        self.fontSizeBox = QtGui.QSpinBox(self.tab_edit)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fontSizeBox.sizePolicy().hasHeightForWidth())
        self.fontSizeBox.setSizePolicy(sizePolicy)
        self.fontSizeBox.setMinimumSize(QtCore.QSize(86, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fontSizeBox.setFont(font)
        self.fontSizeBox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.fontSizeBox.setMinimum(10)
        self.fontSizeBox.setMaximum(80)
        self.fontSizeBox.setProperty("value", 16)
        self.fontSizeBox.setObjectName(_fromUtf8("fontSizeBox"))
        self.horizontalLayout.addWidget(self.fontSizeBox)
        self.line = QtGui.QFrame(self.tab_edit)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout.addWidget(self.line)
        self.Button_FontColor = QtGui.QToolButton(self.tab_edit)
        self.Button_FontColor.setMinimumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_FontColor.setFont(font)
        self.Button_FontColor.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_FontColor.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit_tool/pic/editor/534836.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_FontColor.setIcon(icon5)
        self.Button_FontColor.setIconSize(QtCore.QSize(32, 32))
        self.Button_FontColor.setCheckable(False)
        self.Button_FontColor.setChecked(False)
        self.Button_FontColor.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.Button_FontColor.setAutoRaise(True)
        self.Button_FontColor.setArrowType(QtCore.Qt.NoArrow)
        self.Button_FontColor.setObjectName(_fromUtf8("Button_FontColor"))
        self.horizontalLayout.addWidget(self.Button_FontColor)
        self.Button_BackColor = QtGui.QToolButton(self.tab_edit)
        self.Button_BackColor.setMinimumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_BackColor.setFont(font)
        self.Button_BackColor.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_BackColor.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit_tool/pic/editor/534843.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_BackColor.setIcon(icon6)
        self.Button_BackColor.setIconSize(QtCore.QSize(32, 32))
        self.Button_BackColor.setCheckable(False)
        self.Button_BackColor.setChecked(False)
        self.Button_BackColor.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.Button_BackColor.setAutoRaise(True)
        self.Button_BackColor.setArrowType(QtCore.Qt.NoArrow)
        self.Button_BackColor.setObjectName(_fromUtf8("Button_BackColor"))
        self.horizontalLayout.addWidget(self.Button_BackColor)
        self.line_2 = QtGui.QFrame(self.tab_edit)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout.addWidget(self.line_2)
        self.Button_B = QtGui.QToolButton(self.tab_edit)
        self.Button_B.setMinimumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_B.setFont(font)
        self.Button_B.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_B.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit_tool/pic/editor/534873.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_B.setIcon(icon7)
        self.Button_B.setIconSize(QtCore.QSize(32, 32))
        self.Button_B.setCheckable(True)
        self.Button_B.setChecked(False)
        self.Button_B.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.Button_B.setAutoRaise(True)
        self.Button_B.setArrowType(QtCore.Qt.NoArrow)
        self.Button_B.setObjectName(_fromUtf8("Button_B"))
        self.horizontalLayout.addWidget(self.Button_B)
        self.Button_I = QtGui.QToolButton(self.tab_edit)
        self.Button_I.setMinimumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_I.setFont(font)
        self.Button_I.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_I.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit_tool/pic/editor/534860.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_I.setIcon(icon8)
        self.Button_I.setIconSize(QtCore.QSize(32, 32))
        self.Button_I.setCheckable(True)
        self.Button_I.setAutoRaise(True)
        self.Button_I.setObjectName(_fromUtf8("Button_I"))
        self.horizontalLayout.addWidget(self.Button_I)
        self.Button_U = QtGui.QToolButton(self.tab_edit)
        self.Button_U.setMinimumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_U.setFont(font)
        self.Button_U.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_U.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit_tool/pic/editor/534835.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_U.setIcon(icon9)
        self.Button_U.setIconSize(QtCore.QSize(32, 32))
        self.Button_U.setCheckable(True)
        self.Button_U.setAutoRaise(True)
        self.Button_U.setObjectName(_fromUtf8("Button_U"))
        self.horizontalLayout.addWidget(self.Button_U)
        self.line_3 = QtGui.QFrame(self.tab_edit)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout.addWidget(self.line_3)
        self.Button_Undo = QtGui.QToolButton(self.tab_edit)
        self.Button_Undo.setMinimumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_Undo.setFont(font)
        self.Button_Undo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_Undo.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit_tool/pic/tools/editundo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_Undo.setIcon(icon10)
        self.Button_Undo.setIconSize(QtCore.QSize(32, 32))
        self.Button_Undo.setCheckable(False)
        self.Button_Undo.setChecked(False)
        self.Button_Undo.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.Button_Undo.setAutoRaise(True)
        self.Button_Undo.setArrowType(QtCore.Qt.NoArrow)
        self.Button_Undo.setObjectName(_fromUtf8("Button_Undo"))
        self.horizontalLayout.addWidget(self.Button_Undo)
        self.Button_Redo = QtGui.QToolButton(self.tab_edit)
        self.Button_Redo.setMinimumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_Redo.setFont(font)
        self.Button_Redo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_Redo.setText(_fromUtf8(""))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit_tool/pic/tools/editredo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_Redo.setIcon(icon11)
        self.Button_Redo.setIconSize(QtCore.QSize(32, 32))
        self.Button_Redo.setCheckable(False)
        self.Button_Redo.setChecked(False)
        self.Button_Redo.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.Button_Redo.setAutoRaise(True)
        self.Button_Redo.setArrowType(QtCore.Qt.NoArrow)
        self.Button_Redo.setObjectName(_fromUtf8("Button_Redo"))
        self.horizontalLayout.addWidget(self.Button_Redo)
        self.line_4 = QtGui.QFrame(self.tab_edit)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout.addWidget(self.line_4)
        self.Button_Align = QtGui.QToolButton(self.tab_edit)
        self.Button_Align.setMinimumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_Align.setFont(font)
        self.Button_Align.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_Align.setText(_fromUtf8(""))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit_tool/pic/tools/textjustify.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_Align.setIcon(icon12)
        self.Button_Align.setIconSize(QtCore.QSize(32, 32))
        self.Button_Align.setCheckable(False)
        self.Button_Align.setChecked(False)
        self.Button_Align.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.Button_Align.setAutoRaise(True)
        self.Button_Align.setArrowType(QtCore.Qt.NoArrow)
        self.Button_Align.setObjectName(_fromUtf8("Button_Align"))
        self.horizontalLayout.addWidget(self.Button_Align)
        self.line_6 = QtGui.QFrame(self.tab_edit)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.horizontalLayout.addWidget(self.line_6)
        self.Button_AddPic = QtGui.QToolButton(self.tab_edit)
        self.Button_AddPic.setMinimumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_AddPic.setFont(font)
        self.Button_AddPic.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_AddPic.setText(_fromUtf8(""))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit_tool/pic/editor/534862.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_AddPic.setIcon(icon13)
        self.Button_AddPic.setIconSize(QtCore.QSize(32, 32))
        self.Button_AddPic.setCheckable(False)
        self.Button_AddPic.setChecked(False)
        self.Button_AddPic.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.Button_AddPic.setAutoRaise(True)
        self.Button_AddPic.setArrowType(QtCore.Qt.NoArrow)
        self.Button_AddPic.setObjectName(_fromUtf8("Button_AddPic"))
        self.horizontalLayout.addWidget(self.Button_AddPic)
        self.Button_AddTable = QtGui.QToolButton(self.tab_edit)
        self.Button_AddTable.setMinimumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_AddTable.setFont(font)
        self.Button_AddTable.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_AddTable.setText(_fromUtf8(""))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit_tool/pic/editor/534837.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_AddTable.setIcon(icon14)
        self.Button_AddTable.setIconSize(QtCore.QSize(32, 32))
        self.Button_AddTable.setCheckable(False)
        self.Button_AddTable.setChecked(False)
        self.Button_AddTable.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.Button_AddTable.setAutoRaise(True)
        self.Button_AddTable.setArrowType(QtCore.Qt.NoArrow)
        self.Button_AddTable.setObjectName(_fromUtf8("Button_AddTable"))
        self.horizontalLayout.addWidget(self.Button_AddTable)
        self.Button_AddLink = QtGui.QToolButton(self.tab_edit)
        self.Button_AddLink.setMinimumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_AddLink.setFont(font)
        self.Button_AddLink.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_AddLink.setText(_fromUtf8(""))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit_tool/pic/editor/534861.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_AddLink.setIcon(icon15)
        self.Button_AddLink.setIconSize(QtCore.QSize(32, 32))
        self.Button_AddLink.setCheckable(False)
        self.Button_AddLink.setChecked(False)
        self.Button_AddLink.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.Button_AddLink.setAutoRaise(True)
        self.Button_AddLink.setArrowType(QtCore.Qt.NoArrow)
        self.Button_AddLink.setObjectName(_fromUtf8("Button_AddLink"))
        self.horizontalLayout.addWidget(self.Button_AddLink)
        self.line_7 = QtGui.QFrame(self.tab_edit)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.horizontalLayout.addWidget(self.line_7)
        self.Button_AddList2 = QtGui.QToolButton(self.tab_edit)
        self.Button_AddList2.setMinimumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_AddList2.setFont(font)
        self.Button_AddList2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_AddList2.setText(_fromUtf8(""))
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit_tool/pic/editor/534856.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_AddList2.setIcon(icon16)
        self.Button_AddList2.setIconSize(QtCore.QSize(32, 32))
        self.Button_AddList2.setCheckable(False)
        self.Button_AddList2.setChecked(False)
        self.Button_AddList2.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.Button_AddList2.setAutoRaise(True)
        self.Button_AddList2.setArrowType(QtCore.Qt.NoArrow)
        self.Button_AddList2.setObjectName(_fromUtf8("Button_AddList2"))
        self.horizontalLayout.addWidget(self.Button_AddList2)
        self.Button_AddList = QtGui.QToolButton(self.tab_edit)
        self.Button_AddList.setMinimumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_AddList.setFont(font)
        self.Button_AddList.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_AddList.setText(_fromUtf8(""))
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit_tool/pic/editor/534872.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_AddList.setIcon(icon17)
        self.Button_AddList.setIconSize(QtCore.QSize(32, 32))
        self.Button_AddList.setCheckable(False)
        self.Button_AddList.setChecked(False)
        self.Button_AddList.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.Button_AddList.setAutoRaise(True)
        self.Button_AddList.setArrowType(QtCore.Qt.NoArrow)
        self.Button_AddList.setObjectName(_fromUtf8("Button_AddList"))
        self.horizontalLayout.addWidget(self.Button_AddList)
        self.line_5 = QtGui.QFrame(self.tab_edit)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.horizontalLayout.addWidget(self.line_5)
        self.Button_SetUp = QtGui.QToolButton(self.tab_edit)
        self.Button_SetUp.setMinimumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_SetUp.setFont(font)
        self.Button_SetUp.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_SetUp.setText(_fromUtf8(""))
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit_tool/pic/editor/534839.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_SetUp.setIcon(icon18)
        self.Button_SetUp.setIconSize(QtCore.QSize(32, 32))
        self.Button_SetUp.setCheckable(True)
        self.Button_SetUp.setChecked(False)
        self.Button_SetUp.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.Button_SetUp.setAutoRaise(True)
        self.Button_SetUp.setArrowType(QtCore.Qt.NoArrow)
        self.Button_SetUp.setObjectName(_fromUtf8("Button_SetUp"))
        self.horizontalLayout.addWidget(self.Button_SetUp)
        self.Button_SetDown = QtGui.QToolButton(self.tab_edit)
        self.Button_SetDown.setMinimumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_SetDown.setFont(font)
        self.Button_SetDown.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_SetDown.setText(_fromUtf8(""))
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit_tool/pic/editor/534838.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_SetDown.setIcon(icon19)
        self.Button_SetDown.setIconSize(QtCore.QSize(32, 32))
        self.Button_SetDown.setCheckable(True)
        self.Button_SetDown.setChecked(False)
        self.Button_SetDown.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.Button_SetDown.setAutoRaise(True)
        self.Button_SetDown.setArrowType(QtCore.Qt.NoArrow)
        self.Button_SetDown.setObjectName(_fromUtf8("Button_SetDown"))
        self.horizontalLayout.addWidget(self.Button_SetDown)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textEdit = QtGui.QTextEdit(self.tab_edit)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMinimumSize(QtCore.QSize(1146, 543))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout.addWidget(self.textEdit)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tab_edit, _fromUtf8(""))
        self.tab_html = QtGui.QWidget()
        self.tab_html.setObjectName(_fromUtf8("tab_html"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab_html)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.PlainTextEdit_Html = QtGui.QPlainTextEdit(self.tab_html)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PlainTextEdit_Html.setFont(font)
        self.PlainTextEdit_Html.setPlainText(_fromUtf8(""))
        self.PlainTextEdit_Html.setObjectName(_fromUtf8("PlainTextEdit_Html"))
        self.horizontalLayout_2.addWidget(self.PlainTextEdit_Html)
        self.tabWidget.addTab(self.tab_html, _fromUtf8(""))
        self.tab_appendix = QtGui.QWidget()
        self.tab_appendix.setObjectName(_fromUtf8("tab_appendix"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.tab_appendix)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.Button_AddAppend = QtGui.QCommandLinkButton(self.tab_appendix)
        self.Button_AddAppend.setMinimumSize(QtCore.QSize(111, 0))
        self.Button_AddAppend.setMaximumSize(QtCore.QSize(111, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(12)
        self.Button_AddAppend.setFont(font)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/r_icon/pic/r_icon/Add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_AddAppend.setIcon(icon20)
        self.Button_AddAppend.setIconSize(QtCore.QSize(24, 24))
        self.Button_AddAppend.setObjectName(_fromUtf8("Button_AddAppend"))
        self.horizontalLayout_8.addWidget(self.Button_AddAppend)
        self.Button_DelAppend = QtGui.QCommandLinkButton(self.tab_appendix)
        self.Button_DelAppend.setMinimumSize(QtCore.QSize(111, 0))
        self.Button_DelAppend.setMaximumSize(QtCore.QSize(111, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(12)
        self.Button_DelAppend.setFont(font)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8(":/r_icon/pic/r_icon/Denided.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_DelAppend.setIcon(icon21)
        self.Button_DelAppend.setIconSize(QtCore.QSize(24, 24))
        self.Button_DelAppend.setObjectName(_fromUtf8("Button_DelAppend"))
        self.horizontalLayout_8.addWidget(self.Button_DelAppend)
        spacerItem1 = QtGui.QSpacerItem(753, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.Button_UpdateAppend = QtGui.QPushButton(self.tab_appendix)
        self.Button_UpdateAppend.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_UpdateAppend.setFont(font)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(_fromUtf8(":/r_icon/pic/ico/refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_UpdateAppend.setIcon(icon22)
        self.Button_UpdateAppend.setIconSize(QtCore.QSize(28, 28))
        self.Button_UpdateAppend.setFlat(True)
        self.Button_UpdateAppend.setObjectName(_fromUtf8("Button_UpdateAppend"))
        self.horizontalLayout_8.addWidget(self.Button_UpdateAppend)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.table_Appendix = QtGui.QTableWidget(self.tab_appendix)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.table_Appendix.setFont(font)
        self.table_Appendix.setObjectName(_fromUtf8("table_Appendix"))
        self.table_Appendix.setColumnCount(0)
        self.table_Appendix.setRowCount(0)
        self.verticalLayout_2.addWidget(self.table_Appendix)
        self.horizontalLayout_10.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tab_appendix, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.tabWidget)

        self.retranslateUi(Dialog_Editor)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.Button_Undo, QtCore.SIGNAL(_fromUtf8("clicked()")), self.textEdit.undo)
        QtCore.QObject.connect(self.Button_Redo, QtCore.SIGNAL(_fromUtf8("clicked()")), self.textEdit.redo)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Editor)

    def retranslateUi(self, Dialog_Editor):
        Dialog_Editor.setWindowTitle(_translate("Dialog_Editor", "编辑邮件内容", None))
        self.Button_OK.setText(_translate("Dialog_Editor", "完成", None))
        self.Button_Cancel.setText(_translate("Dialog_Editor", "取消", None))
        self.Button_Save.setText(_translate("Dialog_Editor", "保存", None))
        self.Button_Appendix.setText(_translate("Dialog_Editor", "附件", None))
        self.label.setText(_translate("Dialog_Editor", "主题：", None))
        self.Button_FontColor.setToolTip(_translate("Dialog_Editor", "字体颜色", None))
        self.Button_BackColor.setToolTip(_translate("Dialog_Editor", "字体背景色", None))
        self.Button_B.setToolTip(_translate("Dialog_Editor", "粗体", None))
        self.Button_I.setToolTip(_translate("Dialog_Editor", "斜体", None))
        self.Button_U.setToolTip(_translate("Dialog_Editor", "下划线", None))
        self.Button_Undo.setToolTip(_translate("Dialog_Editor", "撤销", None))
        self.Button_Redo.setToolTip(_translate("Dialog_Editor", "删除", None))
        self.Button_Align.setToolTip(_translate("Dialog_Editor", "对齐方式", None))
        self.Button_AddPic.setToolTip(_translate("Dialog_Editor", "插入图片", None))
        self.Button_AddTable.setToolTip(_translate("Dialog_Editor", "插入表格", None))
        self.Button_AddLink.setToolTip(_translate("Dialog_Editor", "插入超链接", None))
        self.Button_AddList2.setToolTip(_translate("Dialog_Editor", "插入列表", None))
        self.Button_AddList.setToolTip(_translate("Dialog_Editor", "插入列表", None))
        self.Button_SetUp.setToolTip(_translate("Dialog_Editor", "上标", None))
        self.Button_SetDown.setToolTip(_translate("Dialog_Editor", "下标", None))
        self.textEdit.setHtml(_translate("Dialog_Editor", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_edit), _translate("Dialog_Editor", "编辑", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_html), _translate("Dialog_Editor", "html", None))
        self.Button_AddAppend.setText(_translate("Dialog_Editor", "添加附件", None))
        self.Button_DelAppend.setText(_translate("Dialog_Editor", "删除附件", None))
        self.Button_UpdateAppend.setText(_translate("Dialog_Editor", "刷新", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_appendix), _translate("Dialog_Editor", "附件", None))

import send1_rc
