# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editor.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog_Editor(object):
    def setupUi(self, Dialog_Editor):
        Dialog_Editor.setObjectName(_fromUtf8("Dialog_Editor"))
        Dialog_Editor.resize(1171, 797)
        self.tabWidget = QtGui.QTabWidget(Dialog_Editor)
        self.tabWidget.setGeometry(QtCore.QRect(0, 170, 1166, 626))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.Button_AddPic = QtGui.QToolButton(self.tab)
        self.Button_AddPic.setGeometry(QtCore.QRect(745, 0, 56, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_AddPic.setFont(font)
        self.Button_AddPic.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_AddPic.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit_tool/pic/editor/534862.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_AddPic.setIcon(icon)
        self.Button_AddPic.setIconSize(QtCore.QSize(32, 32))
        self.Button_AddPic.setCheckable(False)
        self.Button_AddPic.setChecked(False)
        self.Button_AddPic.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.Button_AddPic.setAutoRaise(True)
        self.Button_AddPic.setArrowType(QtCore.Qt.NoArrow)
        self.Button_AddPic.setObjectName(_fromUtf8("Button_AddPic"))
        self.line = QtGui.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(246, -5, 10, 56))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(375, 0, 11, 51))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.textEdit = QtGui.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(5, 55, 1146, 541))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.fontSizeBox = QtGui.QSpinBox(self.tab)
        self.fontSizeBox.setGeometry(QtCore.QRect(145, 10, 86, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fontSizeBox.setFont(font)
        self.fontSizeBox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.fontSizeBox.setMinimum(10)
        self.fontSizeBox.setMaximum(80)
        self.fontSizeBox.setProperty("value", 16)
        self.fontSizeBox.setObjectName(_fromUtf8("fontSizeBox"))
        self.Button_U = QtGui.QToolButton(self.tab)
        self.Button_U.setGeometry(QtCore.QRect(495, 0, 56, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_U.setFont(font)
        self.Button_U.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_U.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit_tool/pic/editor/534835.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_U.setIcon(icon1)
        self.Button_U.setIconSize(QtCore.QSize(32, 32))
        self.Button_U.setCheckable(True)
        self.Button_U.setAutoRaise(True)
        self.Button_U.setObjectName(_fromUtf8("Button_U"))
        self.fontBox = QtGui.QFontComboBox(self.tab)
        self.fontBox.setGeometry(QtCore.QRect(10, 10, 116, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.fontBox.setFont(font)
        self.fontBox.setFocusPolicy(QtCore.Qt.ClickFocus)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("SimSun-ExtB"))
        font.setPointSize(9)
        self.fontBox.setCurrentFont(font)
        self.fontBox.setObjectName(_fromUtf8("fontBox"))
        self.Button_I = QtGui.QToolButton(self.tab)
        self.Button_I.setGeometry(QtCore.QRect(440, 0, 56, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_I.setFont(font)
        self.Button_I.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_I.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit_tool/pic/editor/534860.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_I.setIcon(icon2)
        self.Button_I.setIconSize(QtCore.QSize(32, 32))
        self.Button_I.setCheckable(True)
        self.Button_I.setAutoRaise(True)
        self.Button_I.setObjectName(_fromUtf8("Button_I"))
        self.Button_B = QtGui.QToolButton(self.tab)
        self.Button_B.setGeometry(QtCore.QRect(385, 0, 56, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_B.setFont(font)
        self.Button_B.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_B.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit_tool/pic/editor/534873.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_B.setIcon(icon3)
        self.Button_B.setIconSize(QtCore.QSize(32, 32))
        self.Button_B.setCheckable(True)
        self.Button_B.setChecked(False)
        self.Button_B.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.Button_B.setAutoRaise(True)
        self.Button_B.setArrowType(QtCore.Qt.NoArrow)
        self.Button_B.setObjectName(_fromUtf8("Button_B"))
        self.line_3 = QtGui.QFrame(self.tab)
        self.line_3.setGeometry(QtCore.QRect(550, 0, 10, 51))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.Button_FontColor = QtGui.QToolButton(self.tab)
        self.Button_FontColor.setGeometry(QtCore.QRect(255, 0, 56, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_FontColor.setFont(font)
        self.Button_FontColor.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_FontColor.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit_tool/pic/editor/534836.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_FontColor.setIcon(icon4)
        self.Button_FontColor.setIconSize(QtCore.QSize(32, 32))
        self.Button_FontColor.setCheckable(False)
        self.Button_FontColor.setChecked(False)
        self.Button_FontColor.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.Button_FontColor.setAutoRaise(True)
        self.Button_FontColor.setArrowType(QtCore.Qt.NoArrow)
        self.Button_FontColor.setObjectName(_fromUtf8("Button_FontColor"))
        self.Button_AddTable = QtGui.QToolButton(self.tab)
        self.Button_AddTable.setGeometry(QtCore.QRect(800, 0, 56, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_AddTable.setFont(font)
        self.Button_AddTable.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_AddTable.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit_tool/pic/editor/534837.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_AddTable.setIcon(icon5)
        self.Button_AddTable.setIconSize(QtCore.QSize(32, 32))
        self.Button_AddTable.setCheckable(False)
        self.Button_AddTable.setChecked(False)
        self.Button_AddTable.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.Button_AddTable.setAutoRaise(True)
        self.Button_AddTable.setArrowType(QtCore.Qt.NoArrow)
        self.Button_AddTable.setObjectName(_fromUtf8("Button_AddTable"))
        self.Button_AddList = QtGui.QToolButton(self.tab)
        self.Button_AddList.setGeometry(QtCore.QRect(855, 0, 56, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_AddList.setFont(font)
        self.Button_AddList.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_AddList.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit_tool/pic/editor/534872.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_AddList.setIcon(icon6)
        self.Button_AddList.setIconSize(QtCore.QSize(32, 32))
        self.Button_AddList.setCheckable(False)
        self.Button_AddList.setChecked(False)
        self.Button_AddList.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.Button_AddList.setAutoRaise(True)
        self.Button_AddList.setArrowType(QtCore.Qt.NoArrow)
        self.Button_AddList.setObjectName(_fromUtf8("Button_AddList"))
        self.Button_AddList2 = QtGui.QToolButton(self.tab)
        self.Button_AddList2.setGeometry(QtCore.QRect(910, 0, 56, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_AddList2.setFont(font)
        self.Button_AddList2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_AddList2.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit_tool/pic/editor/534856.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_AddList2.setIcon(icon7)
        self.Button_AddList2.setIconSize(QtCore.QSize(32, 32))
        self.Button_AddList2.setCheckable(False)
        self.Button_AddList2.setChecked(False)
        self.Button_AddList2.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.Button_AddList2.setAutoRaise(True)
        self.Button_AddList2.setArrowType(QtCore.Qt.NoArrow)
        self.Button_AddList2.setObjectName(_fromUtf8("Button_AddList2"))
        self.Button_SetUp = QtGui.QToolButton(self.tab)
        self.Button_SetUp.setGeometry(QtCore.QRect(1030, 0, 56, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_SetUp.setFont(font)
        self.Button_SetUp.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_SetUp.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit_tool/pic/editor/534839.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_SetUp.setIcon(icon8)
        self.Button_SetUp.setIconSize(QtCore.QSize(32, 32))
        self.Button_SetUp.setCheckable(True)
        self.Button_SetUp.setChecked(False)
        self.Button_SetUp.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.Button_SetUp.setAutoRaise(True)
        self.Button_SetUp.setArrowType(QtCore.Qt.NoArrow)
        self.Button_SetUp.setObjectName(_fromUtf8("Button_SetUp"))
        self.Button_SetDown = QtGui.QToolButton(self.tab)
        self.Button_SetDown.setGeometry(QtCore.QRect(1085, 0, 56, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_SetDown.setFont(font)
        self.Button_SetDown.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_SetDown.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit_tool/pic/editor/534838.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_SetDown.setIcon(icon9)
        self.Button_SetDown.setIconSize(QtCore.QSize(32, 32))
        self.Button_SetDown.setCheckable(True)
        self.Button_SetDown.setChecked(False)
        self.Button_SetDown.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.Button_SetDown.setAutoRaise(True)
        self.Button_SetDown.setArrowType(QtCore.Qt.NoArrow)
        self.Button_SetDown.setObjectName(_fromUtf8("Button_SetDown"))
        self.Button_BackColor = QtGui.QToolButton(self.tab)
        self.Button_BackColor.setGeometry(QtCore.QRect(320, 0, 56, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_BackColor.setFont(font)
        self.Button_BackColor.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_BackColor.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit_tool/pic/editor/534843.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_BackColor.setIcon(icon10)
        self.Button_BackColor.setIconSize(QtCore.QSize(32, 32))
        self.Button_BackColor.setCheckable(False)
        self.Button_BackColor.setChecked(False)
        self.Button_BackColor.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.Button_BackColor.setAutoRaise(True)
        self.Button_BackColor.setArrowType(QtCore.Qt.NoArrow)
        self.Button_BackColor.setObjectName(_fromUtf8("Button_BackColor"))
        self.Button_Undo = QtGui.QToolButton(self.tab)
        self.Button_Undo.setGeometry(QtCore.QRect(560, 0, 56, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_Undo.setFont(font)
        self.Button_Undo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_Undo.setText(_fromUtf8(""))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit_tool/pic/tools/editundo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_Undo.setIcon(icon11)
        self.Button_Undo.setIconSize(QtCore.QSize(32, 32))
        self.Button_Undo.setCheckable(False)
        self.Button_Undo.setChecked(False)
        self.Button_Undo.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.Button_Undo.setAutoRaise(True)
        self.Button_Undo.setArrowType(QtCore.Qt.NoArrow)
        self.Button_Undo.setObjectName(_fromUtf8("Button_Undo"))
        self.Button_Redo = QtGui.QToolButton(self.tab)
        self.Button_Redo.setGeometry(QtCore.QRect(615, 0, 56, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_Redo.setFont(font)
        self.Button_Redo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_Redo.setText(_fromUtf8(""))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit_tool/pic/tools/editredo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_Redo.setIcon(icon12)
        self.Button_Redo.setIconSize(QtCore.QSize(32, 32))
        self.Button_Redo.setCheckable(False)
        self.Button_Redo.setChecked(False)
        self.Button_Redo.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.Button_Redo.setAutoRaise(True)
        self.Button_Redo.setArrowType(QtCore.Qt.NoArrow)
        self.Button_Redo.setObjectName(_fromUtf8("Button_Redo"))
        self.line_4 = QtGui.QFrame(self.tab)
        self.line_4.setGeometry(QtCore.QRect(670, 0, 10, 51))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.Button_AddLink = QtGui.QToolButton(self.tab)
        self.Button_AddLink.setGeometry(QtCore.QRect(965, 0, 56, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_AddLink.setFont(font)
        self.Button_AddLink.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_AddLink.setText(_fromUtf8(""))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit_tool/pic/editor/534861.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_AddLink.setIcon(icon13)
        self.Button_AddLink.setIconSize(QtCore.QSize(32, 32))
        self.Button_AddLink.setCheckable(False)
        self.Button_AddLink.setChecked(False)
        self.Button_AddLink.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.Button_AddLink.setAutoRaise(True)
        self.Button_AddLink.setArrowType(QtCore.Qt.NoArrow)
        self.Button_AddLink.setObjectName(_fromUtf8("Button_AddLink"))
        self.line_5 = QtGui.QFrame(self.tab)
        self.line_5.setGeometry(QtCore.QRect(1020, 0, 10, 51))
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.Button_Align = QtGui.QToolButton(self.tab)
        self.Button_Align.setGeometry(QtCore.QRect(680, 0, 56, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_Align.setFont(font)
        self.Button_Align.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Button_Align.setText(_fromUtf8(""))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit_tool/pic/tools/textjustify.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_Align.setIcon(icon14)
        self.Button_Align.setIconSize(QtCore.QSize(32, 32))
        self.Button_Align.setCheckable(False)
        self.Button_Align.setChecked(False)
        self.Button_Align.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.Button_Align.setAutoRaise(True)
        self.Button_Align.setArrowType(QtCore.Qt.NoArrow)
        self.Button_Align.setObjectName(_fromUtf8("Button_Align"))
        self.line_6 = QtGui.QFrame(self.tab)
        self.line_6.setGeometry(QtCore.QRect(735, 0, 10, 51))
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.PlainTextEdit_Html = QtGui.QPlainTextEdit(self.tab_2)
        self.PlainTextEdit_Html.setGeometry(QtCore.QRect(5, 5, 1146, 591))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PlainTextEdit_Html.setFont(font)
        self.PlainTextEdit_Html.setPlainText(_fromUtf8(""))
        self.PlainTextEdit_Html.setObjectName(_fromUtf8("PlainTextEdit_Html"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.lineEdit = QtGui.QLineEdit(Dialog_Editor)
        self.lineEdit.setGeometry(QtCore.QRect(75, 125, 1086, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit.setFont(font)
        self.lineEdit.setText(_fromUtf8(""))
        self.lineEdit.setFrame(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.label = QtGui.QLabel(Dialog_Editor)
        self.label.setGeometry(QtCore.QRect(10, 130, 61, 36))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("SimSun-ExtB"))
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))

        self.retranslateUi(Dialog_Editor)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.Button_Undo, QtCore.SIGNAL(_fromUtf8("clicked()")), self.textEdit.undo)
        QtCore.QObject.connect(self.Button_Redo, QtCore.SIGNAL(_fromUtf8("clicked()")), self.textEdit.redo)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Editor)

    def retranslateUi(self, Dialog_Editor):
        Dialog_Editor.setWindowTitle(_translate("Dialog_Editor", "Dialog", None))
        self.Button_AddPic.setToolTip(_translate("Dialog_Editor", "插入图片", None))
        self.textEdit.setHtml(_translate("Dialog_Editor", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.Button_U.setToolTip(_translate("Dialog_Editor", "下划线", None))
        self.Button_I.setToolTip(_translate("Dialog_Editor", "斜体", None))
        self.Button_B.setToolTip(_translate("Dialog_Editor", "粗体", None))
        self.Button_FontColor.setToolTip(_translate("Dialog_Editor", "字体颜色", None))
        self.Button_AddTable.setToolTip(_translate("Dialog_Editor", "插入表格", None))
        self.Button_AddList.setToolTip(_translate("Dialog_Editor", "插入列表", None))
        self.Button_AddList2.setToolTip(_translate("Dialog_Editor", "插入列表", None))
        self.Button_SetUp.setToolTip(_translate("Dialog_Editor", "上标", None))
        self.Button_SetDown.setToolTip(_translate("Dialog_Editor", "下标", None))
        self.Button_BackColor.setToolTip(_translate("Dialog_Editor", "字体背景色", None))
        self.Button_Undo.setToolTip(_translate("Dialog_Editor", "撤销", None))
        self.Button_Redo.setToolTip(_translate("Dialog_Editor", "删除", None))
        self.Button_AddLink.setToolTip(_translate("Dialog_Editor", "插入超链接", None))
        self.Button_Align.setToolTip(_translate("Dialog_Editor", "对齐方式", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog_Editor", "编辑", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog_Editor", "html", None))
        self.label.setText(_translate("Dialog_Editor", "主题：", None))

import send1_rc
