# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editor_add_table.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog_AddTable(object):
    def setupUi(self, Dialog_AddTable):
        Dialog_AddTable.setObjectName(_fromUtf8("Dialog_AddTable"))
        Dialog_AddTable.resize(416, 329)
        Dialog_AddTable.setMinimumSize(QtCore.QSize(338, 255))
        Dialog_AddTable.setMaximumSize(QtCore.QSize(16777215, 16777213))
        self.label = QtGui.QLabel(Dialog_AddTable)
        self.label.setGeometry(QtCore.QRect(20, 19, 46, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(Dialog_AddTable)
        self.label_2.setGeometry(QtCore.QRect(230, 19, 46, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.Box_Row = QtGui.QSpinBox(Dialog_AddTable)
        self.Box_Row.setGeometry(QtCore.QRect(65, 20, 76, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Box_Row.setFont(font)
        self.Box_Row.setProperty("value", 3)
        self.Box_Row.setObjectName(_fromUtf8("Box_Row"))
        self.Box_Column = QtGui.QSpinBox(Dialog_AddTable)
        self.Box_Column.setGeometry(QtCore.QRect(280, 20, 76, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Box_Column.setFont(font)
        self.Box_Column.setProperty("value", 4)
        self.Box_Column.setObjectName(_fromUtf8("Box_Column"))
        self.label_3 = QtGui.QLabel(Dialog_AddTable)
        self.label_3.setGeometry(QtCore.QRect(20, 65, 86, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.radioButton_Left = QtGui.QRadioButton(Dialog_AddTable)
        self.radioButton_Left.setGeometry(QtCore.QRect(110, 65, 61, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_Left.setFont(font)
        self.radioButton_Left.setIconSize(QtCore.QSize(32, 32))
        self.radioButton_Left.setChecked(True)
        self.radioButton_Left.setObjectName(_fromUtf8("radioButton_Left"))
        self.buttonGroup = QtGui.QButtonGroup(Dialog_AddTable)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.radioButton_Left)
        self.radioButton_Mid = QtGui.QRadioButton(Dialog_AddTable)
        self.radioButton_Mid.setGeometry(QtCore.QRect(190, 65, 61, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_Mid.setFont(font)
        self.radioButton_Mid.setIconSize(QtCore.QSize(32, 32))
        self.radioButton_Mid.setObjectName(_fromUtf8("radioButton_Mid"))
        self.buttonGroup.addButton(self.radioButton_Mid)
        self.radioButton_Right = QtGui.QRadioButton(Dialog_AddTable)
        self.radioButton_Right.setGeometry(QtCore.QRect(270, 65, 61, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_Right.setFont(font)
        self.radioButton_Right.setIconSize(QtCore.QSize(32, 32))
        self.radioButton_Right.setObjectName(_fromUtf8("radioButton_Right"))
        self.buttonGroup.addButton(self.radioButton_Right)
        self.label_4 = QtGui.QLabel(Dialog_AddTable)
        self.label_4.setGeometry(QtCore.QRect(20, 185, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.Box_Padding = QtGui.QSpinBox(Dialog_AddTable)
        self.Box_Padding.setGeometry(QtCore.QRect(265, 190, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Box_Padding.setFont(font)
        self.Box_Padding.setMaximum(399)
        self.Box_Padding.setProperty("value", 8)
        self.Box_Padding.setObjectName(_fromUtf8("Box_Padding"))
        self.label_5 = QtGui.QLabel(Dialog_AddTable)
        self.label_5.setGeometry(QtCore.QRect(350, 185, 46, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(Dialog_AddTable)
        self.label_6.setGeometry(QtCore.QRect(20, 225, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.Box_Space = QtGui.QSpinBox(Dialog_AddTable)
        self.Box_Space.setGeometry(QtCore.QRect(265, 230, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Box_Space.setFont(font)
        self.Box_Space.setMaximum(399)
        self.Box_Space.setProperty("value", 0)
        self.Box_Space.setObjectName(_fromUtf8("Box_Space"))
        self.label_7 = QtGui.QLabel(Dialog_AddTable)
        self.label_7.setGeometry(QtCore.QRect(350, 225, 46, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.Button_OK = QtGui.QPushButton(Dialog_AddTable)
        self.Button_OK.setGeometry(QtCore.QRect(100, 275, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Button_OK.setFont(font)
        self.Button_OK.setObjectName(_fromUtf8("Button_OK"))
        self.Button_Cancel = QtGui.QPushButton(Dialog_AddTable)
        self.Button_Cancel.setGeometry(QtCore.QRect(230, 275, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Button_Cancel.setFont(font)
        self.Button_Cancel.setObjectName(_fromUtf8("Button_Cancel"))
        self.label_8 = QtGui.QLabel(Dialog_AddTable)
        self.label_8.setGeometry(QtCore.QRect(20, 145, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.Box_BorderWidth = QtGui.QSpinBox(Dialog_AddTable)
        self.Box_BorderWidth.setGeometry(QtCore.QRect(265, 150, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Box_BorderWidth.setFont(font)
        self.Box_BorderWidth.setMinimum(1)
        self.Box_BorderWidth.setMaximum(399)
        self.Box_BorderWidth.setProperty("value", 2)
        self.Box_BorderWidth.setObjectName(_fromUtf8("Box_BorderWidth"))
        self.label_9 = QtGui.QLabel(Dialog_AddTable)
        self.label_9.setGeometry(QtCore.QRect(350, 145, 46, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(Dialog_AddTable)
        self.label_10.setGeometry(QtCore.QRect(20, 105, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.Button_Color = QtGui.QPushButton(Dialog_AddTable)
        self.Button_Color.setGeometry(QtCore.QRect(265, 110, 121, 31))
        self.Button_Color.setText(_fromUtf8(""))
        self.Button_Color.setIconSize(QtCore.QSize(128, 128))
        self.Button_Color.setFlat(True)
        self.Button_Color.setObjectName(_fromUtf8("Button_Color"))

        self.retranslateUi(Dialog_AddTable)
        QtCore.QMetaObject.connectSlotsByName(Dialog_AddTable)

    def retranslateUi(self, Dialog_AddTable):
        Dialog_AddTable.setWindowTitle(_translate("Dialog_AddTable", "插入表格", None))
        self.label.setText(_translate("Dialog_AddTable", "行：", None))
        self.label_2.setText(_translate("Dialog_AddTable", "列：", None))
        self.label_3.setText(_translate("Dialog_AddTable", "表格位置：", None))
        self.radioButton_Left.setText(_translate("Dialog_AddTable", "左侧", None))
        self.radioButton_Mid.setText(_translate("Dialog_AddTable", "居中", None))
        self.radioButton_Right.setText(_translate("Dialog_AddTable", "右侧", None))
        self.label_4.setText(_translate("Dialog_AddTable", "边框与其内容空白间距：", None))
        self.label_5.setText(_translate("Dialog_AddTable", "像素", None))
        self.label_6.setText(_translate("Dialog_AddTable", "空心边框(0为非空心)：", None))
        self.label_7.setText(_translate("Dialog_AddTable", "像素", None))
        self.Button_OK.setText(_translate("Dialog_AddTable", "确定", None))
        self.Button_Cancel.setText(_translate("Dialog_AddTable", "取消", None))
        self.label_8.setText(_translate("Dialog_AddTable", "边框线粗：", None))
        self.label_9.setText(_translate("Dialog_AddTable", "像素", None))
        self.label_10.setText(_translate("Dialog_AddTable", "边框颜色：", None))

import send1_rc
