# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_send1.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(640, 562)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.pushButton_OK = QtGui.QPushButton(self.centralwidget)
        self.pushButton_OK.setGeometry(QtCore.QRect(140, 470, 131, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        self.pushButton_OK.setFont(font)
        self.pushButton_OK.setObjectName(_fromUtf8("pushButton_OK"))
        self.pushButton_cancel = QtGui.QPushButton(self.centralwidget)
        self.pushButton_cancel.setGeometry(QtCore.QRect(340, 470, 131, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        self.pushButton_cancel.setFont(font)
        self.pushButton_cancel.setObjectName(_fromUtf8("pushButton_cancel"))
        self.label_body = QtGui.QLabel(self.centralwidget)
        self.label_body.setGeometry(QtCore.QRect(110, 110, 401, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(12)
        self.label_body.setFont(font)
        self.label_body.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_body.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_body.setText(_fromUtf8(""))
        self.label_body.setObjectName(_fromUtf8("label_body"))
        self.label_append = QtGui.QLabel(self.centralwidget)
        self.label_append.setGeometry(QtCore.QRect(110, 160, 401, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(12)
        self.label_append.setFont(font)
        self.label_append.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_append.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_append.setText(_fromUtf8(""))
        self.label_append.setObjectName(_fromUtf8("label_append"))
        self.label_maillist = QtGui.QLabel(self.centralwidget)
        self.label_maillist.setGeometry(QtCore.QRect(150, 210, 361, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(12)
        self.label_maillist.setFont(font)
        self.label_maillist.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_maillist.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_maillist.setText(_fromUtf8(""))
        self.label_maillist.setObjectName(_fromUtf8("label_maillist"))
        self.pushButton_body = QtGui.QPushButton(self.centralwidget)
        self.pushButton_body.setGeometry(QtCore.QRect(530, 110, 71, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        self.pushButton_body.setFont(font)
        self.pushButton_body.setObjectName(_fromUtf8("pushButton_body"))
        self.lineEdit_Sub = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_Sub.setGeometry(QtCore.QRect(110, 60, 491, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.lineEdit_Sub.setFont(font)
        self.lineEdit_Sub.setObjectName(_fromUtf8("lineEdit_Sub"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 60, 48, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 110, 42, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 160, 42, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 210, 84, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.pushButton_append = QtGui.QPushButton(self.centralwidget)
        self.pushButton_append.setGeometry(QtCore.QRect(530, 160, 71, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        self.pushButton_append.setFont(font)
        self.pushButton_append.setObjectName(_fromUtf8("pushButton_append"))
        self.pushButton_mail_list = QtGui.QPushButton(self.centralwidget)
        self.pushButton_mail_list.setGeometry(QtCore.QRect(530, 210, 71, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        self.pushButton_mail_list.setFont(font)
        self.pushButton_mail_list.setObjectName(_fromUtf8("pushButton_mail_list"))
        self.lineEdit_Xls_From = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_Xls_From.setGeometry(QtCore.QRect(210, 260, 51, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(14)
        self.lineEdit_Xls_From.setFont(font)
        self.lineEdit_Xls_From.setText(_fromUtf8(""))
        self.lineEdit_Xls_From.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Xls_From.setObjectName(_fromUtf8("lineEdit_Xls_From"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(150, 260, 41, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(270, 260, 84, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(430, 260, 84, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.lineEdit_Xls_To = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_Xls_To.setGeometry(QtCore.QRect(370, 260, 51, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(14)
        self.lineEdit_Xls_To.setFont(font)
        self.lineEdit_Xls_To.setText(_fromUtf8(""))
        self.lineEdit_Xls_To.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Xls_To.setObjectName(_fromUtf8("lineEdit_Xls_To"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(560, 260, 31, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.lineEdit_Xls_Col = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_Xls_Col.setGeometry(QtCore.QRect(490, 260, 51, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(14)
        self.lineEdit_Xls_Col.setFont(font)
        self.lineEdit_Xls_Col.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Xls_Col.setObjectName(_fromUtf8("lineEdit_Xls_Col"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 10, 151, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.pushButton_OK.setText(_translate("MainWindow", "确定", None))
        self.pushButton_cancel.setText(_translate("MainWindow", "退出", None))
        self.pushButton_body.setText(_translate("MainWindow", "浏览..", None))
        self.label_4.setText(_translate("MainWindow", "标题", None))
        self.label_5.setText(_translate("MainWindow", "正文", None))
        self.label_6.setText(_translate("MainWindow", "附件", None))
        self.label_7.setText(_translate("MainWindow", "邮箱列表", None))
        self.pushButton_append.setText(_translate("MainWindow", "浏览..", None))
        self.pushButton_mail_list.setText(_translate("MainWindow", "浏览..", None))
        self.label_8.setText(_translate("MainWindow", "从第", None))
        self.label_9.setText(_translate("MainWindow", "张表到第", None))
        self.label_10.setText(_translate("MainWindow", "张表", None))
        self.label_11.setText(_translate("MainWindow", "列", None))
        self.lineEdit_Xls_Col.setText(_translate("MainWindow", "C", None))
        self.label.setText(_translate("MainWindow", "群发邮件", None))

