# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_send1.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(636, 645)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.pushButton_OK = QtGui.QPushButton(self.centralwidget)
        self.pushButton_OK.setGeometry(QtCore.QRect(140, 540, 131, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        self.pushButton_OK.setFont(font)
        self.pushButton_OK.setObjectName(_fromUtf8("pushButton_OK"))
        self.pushButton_cancel = QtGui.QPushButton(self.centralwidget)
        self.pushButton_cancel.setGeometry(QtCore.QRect(340, 540, 131, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        self.pushButton_cancel.setFont(font)
        self.pushButton_cancel.setObjectName(_fromUtf8("pushButton_cancel"))
        self.label_body = QtGui.QLabel(self.centralwidget)
        self.label_body.setGeometry(QtCore.QRect(110, 110, 401, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(12)
        self.label_body.setFont(font)
        self.label_body.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_body.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_body.setText(_fromUtf8(""))
        self.label_body.setObjectName(_fromUtf8("label_body"))
        self.label_append = QtGui.QLabel(self.centralwidget)
        self.label_append.setGeometry(QtCore.QRect(110, 160, 401, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(12)
        self.label_append.setFont(font)
        self.label_append.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_append.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_append.setText(_fromUtf8(""))
        self.label_append.setObjectName(_fromUtf8("label_append"))
        self.label_maillist = QtGui.QLabel(self.centralwidget)
        self.label_maillist.setGeometry(QtCore.QRect(150, 210, 361, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(12)
        self.label_maillist.setFont(font)
        self.label_maillist.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_maillist.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_maillist.setText(_fromUtf8(""))
        self.label_maillist.setObjectName(_fromUtf8("label_maillist"))
        self.pushButton_body = QtGui.QPushButton(self.centralwidget)
        self.pushButton_body.setGeometry(QtCore.QRect(530, 110, 71, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        self.pushButton_body.setFont(font)
        self.pushButton_body.setObjectName(_fromUtf8("pushButton_body"))
        self.lineEdit_Sub = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_Sub.setGeometry(QtCore.QRect(110, 60, 491, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.lineEdit_Sub.setFont(font)
        self.lineEdit_Sub.setObjectName(_fromUtf8("lineEdit_Sub"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 60, 48, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 110, 42, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 160, 42, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 210, 84, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.pushButton_append = QtGui.QPushButton(self.centralwidget)
        self.pushButton_append.setGeometry(QtCore.QRect(530, 160, 71, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        self.pushButton_append.setFont(font)
        self.pushButton_append.setObjectName(_fromUtf8("pushButton_append"))
        self.pushButton_mail_list = QtGui.QPushButton(self.centralwidget)
        self.pushButton_mail_list.setGeometry(QtCore.QRect(530, 210, 71, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        self.pushButton_mail_list.setFont(font)
        self.pushButton_mail_list.setObjectName(_fromUtf8("pushButton_mail_list"))
        self.lineEdit_Xls_From = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_Xls_From.setGeometry(QtCore.QRect(90, 260, 51, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(14)
        self.lineEdit_Xls_From.setFont(font)
        self.lineEdit_Xls_From.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Xls_From.setObjectName(_fromUtf8("lineEdit_Xls_From"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 260, 41, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(150, 260, 84, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(310, 260, 84, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.lineEdit_Xls_To = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_Xls_To.setGeometry(QtCore.QRect(250, 260, 51, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(14)
        self.lineEdit_Xls_To.setFont(font)
        self.lineEdit_Xls_To.setText(_fromUtf8(""))
        self.lineEdit_Xls_To.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Xls_To.setObjectName(_fromUtf8("lineEdit_Xls_To"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(440, 260, 31, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.lineEdit_Xls_Col = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_Xls_Col.setGeometry(QtCore.QRect(370, 260, 51, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(14)
        self.lineEdit_Xls_Col.setFont(font)
        self.lineEdit_Xls_Col.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Xls_Col.setObjectName(_fromUtf8("lineEdit_Xls_Col"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 10, 331, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.listWidget = QtGui.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(30, 370, 271, 141))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.pushButton_account_add = QtGui.QPushButton(self.centralwidget)
        self.pushButton_account_add.setGeometry(QtCore.QRect(140, 330, 71, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        self.pushButton_account_add.setFont(font)
        self.pushButton_account_add.setObjectName(_fromUtf8("pushButton_account_add"))
        self.pushButton_account_del = QtGui.QPushButton(self.centralwidget)
        self.pushButton_account_del.setGeometry(QtCore.QRect(230, 330, 71, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        self.pushButton_account_del.setFont(font)
        self.pushButton_account_del.setObjectName(_fromUtf8("pushButton_account_del"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(30, 330, 91, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.lineEdit_Sender_Name = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_Sender_Name.setGeometry(QtCore.QRect(470, 330, 131, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.lineEdit_Sender_Name.setFont(font)
        self.lineEdit_Sender_Name.setToolTip(_fromUtf8(""))
        self.lineEdit_Sender_Name.setObjectName(_fromUtf8("lineEdit_Sender_Name"))
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(340, 330, 121, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(340, 390, 121, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(480, 430, 131, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.spinBox_Each_Hour = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_Each_Hour.setGeometry(QtCore.QRect(340, 430, 131, 31))
        self.spinBox_Each_Hour.setMinimumSize(QtCore.QSize(71, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(16)
        self.spinBox_Each_Hour.setFont(font)
        self.spinBox_Each_Hour.setMinimum(1)
        self.spinBox_Each_Hour.setMaximum(2000)
        self.spinBox_Each_Hour.setProperty("value", 400)
        self.spinBox_Each_Hour.setObjectName(_fromUtf8("spinBox_Each_Hour"))
        self.spinBox_Each_Time = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_Each_Time.setGeometry(QtCore.QRect(340, 470, 131, 31))
        self.spinBox_Each_Time.setMinimumSize(QtCore.QSize(71, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(16)
        self.spinBox_Each_Time.setFont(font)
        self.spinBox_Each_Time.setMinimum(1)
        self.spinBox_Each_Time.setMaximum(100)
        self.spinBox_Each_Time.setProperty("value", 40)
        self.spinBox_Each_Time.setObjectName(_fromUtf8("spinBox_Each_Time"))
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(480, 470, 131, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 636, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_Sub, self.pushButton_body)
        MainWindow.setTabOrder(self.pushButton_body, self.pushButton_append)
        MainWindow.setTabOrder(self.pushButton_append, self.pushButton_mail_list)
        MainWindow.setTabOrder(self.pushButton_mail_list, self.lineEdit_Xls_From)
        MainWindow.setTabOrder(self.lineEdit_Xls_From, self.lineEdit_Xls_To)
        MainWindow.setTabOrder(self.lineEdit_Xls_To, self.lineEdit_Xls_Col)
        MainWindow.setTabOrder(self.lineEdit_Xls_Col, self.pushButton_account_add)
        MainWindow.setTabOrder(self.pushButton_account_add, self.pushButton_account_del)
        MainWindow.setTabOrder(self.pushButton_account_del, self.lineEdit_Sender_Name)
        MainWindow.setTabOrder(self.lineEdit_Sender_Name, self.spinBox_Each_Hour)
        MainWindow.setTabOrder(self.spinBox_Each_Hour, self.spinBox_Each_Time)
        MainWindow.setTabOrder(self.spinBox_Each_Time, self.pushButton_OK)
        MainWindow.setTabOrder(self.pushButton_OK, self.pushButton_cancel)
        MainWindow.setTabOrder(self.pushButton_cancel, self.listWidget)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "群发邮件", None))
        self.pushButton_OK.setToolTip(_translate("MainWindow", "开始发送", None))
        self.pushButton_OK.setText(_translate("MainWindow", "开始", None))
        self.pushButton_cancel.setText(_translate("MainWindow", "退出", None))
        self.label_body.setToolTip(_translate("MainWindow", "请打开一个包含邮件正文的txt文件", None))
        self.label_append.setToolTip(_translate("MainWindow", "请打开要发送的附件（可多选）", None))
        self.label_maillist.setToolTip(_translate("MainWindow", "请打存放开收件人Excel表格", None))
        self.pushButton_body.setToolTip(_translate("MainWindow", "请打开一个包含邮件正文的txt文件", None))
        self.pushButton_body.setText(_translate("MainWindow", "浏览..", None))
        self.lineEdit_Sub.setToolTip(_translate("MainWindow", "邮件标题", None))
        self.label_4.setText(_translate("MainWindow", "标题", None))
        self.label_5.setText(_translate("MainWindow", "正文", None))
        self.label_6.setText(_translate("MainWindow", "附件", None))
        self.label_7.setText(_translate("MainWindow", "邮箱列表", None))
        self.pushButton_append.setToolTip(_translate("MainWindow", "请打开要发送的附件（可多选）", None))
        self.pushButton_append.setText(_translate("MainWindow", "浏览..", None))
        self.pushButton_mail_list.setToolTip(_translate("MainWindow", "请打存放开收件人Excel表格", None))
        self.pushButton_mail_list.setText(_translate("MainWindow", "浏览..", None))
        self.lineEdit_Xls_From.setToolTip(_translate("MainWindow", "从1开始计数，第一张表为首张", None))
        self.lineEdit_Xls_From.setText(_translate("MainWindow", "1", None))
        self.label_8.setToolTip(_translate("MainWindow", "邮箱列表保存在Excel表格中的哪几张表，以及哪一列", None))
        self.label_8.setText(_translate("MainWindow", "从第", None))
        self.label_9.setToolTip(_translate("MainWindow", "邮箱列表保存在Excel表格中的哪几张表，以及哪一列", None))
        self.label_9.setText(_translate("MainWindow", "张表到第", None))
        self.label_10.setText(_translate("MainWindow", "张表", None))
        self.lineEdit_Xls_To.setToolTip(_translate("MainWindow", "最后一张(含)", None))
        self.label_11.setText(_translate("MainWindow", "列", None))
        self.lineEdit_Xls_Col.setToolTip(_translate("MainWindow", "保存在哪一列，A,B,C......", None))
        self.lineEdit_Xls_Col.setText(_translate("MainWindow", "C", None))
        self.label.setToolTip(_translate("MainWindow", "Made by D539 Oliver, 1026815245@qq.com", None))
        self.label.setText(_translate("MainWindow", "群发邮件", None))
        self.listWidget.setToolTip(_translate("MainWindow", "多账户将自动切换发送", None))
        self.pushButton_account_add.setToolTip(_translate("MainWindow", "添加一个账户", None))
        self.pushButton_account_add.setText(_translate("MainWindow", "添加", None))
        self.pushButton_account_del.setToolTip(_translate("MainWindow", "删除一个账户", None))
        self.pushButton_account_del.setText(_translate("MainWindow", "删除", None))
        self.label_12.setToolTip(_translate("MainWindow", "多账户将自动切换发送", None))
        self.label_12.setText(_translate("MainWindow", "发送账户", None))
        self.label_13.setText(_translate("MainWindow", "发件人姓名", None))
        self.label_14.setText(_translate("MainWindow", "发送速度", None))
        self.label_15.setToolTip(_translate("MainWindow", "每个账号每小时的发送数量", None))
        self.label_15.setText(_translate("MainWindow", "封/账号/小时", None))
        self.spinBox_Each_Hour.setToolTip(_translate("MainWindow", "每个账号每小时的发送数量", None))
        self.spinBox_Each_Time.setToolTip(_translate("MainWindow", "每一次发送的最大发送数量", None))
        self.label_16.setToolTip(_translate("MainWindow", "每一次发送的最大发送数量", None))
        self.label_16.setText(_translate("MainWindow", "封/次", None))

