# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_send1.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(636, 645)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(636, 645))
        MainWindow.setMaximumSize(QtCore.QSize(636, 645))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        MainWindow.setPalette(palette)
        MainWindow.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(_fromUtf8("#centralwidget {\n"
"\n"
"    background-image: url(:/background/pic/back/linernd.jpg);\n"
"\n"
"}"))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label_body = QtGui.QLabel(self.centralwidget)
        self.label_body.setGeometry(QtCore.QRect(110, 135, 436, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(12)
        self.label_body.setFont(font)
        self.label_body.setFrameShape(QtGui.QFrame.Panel)
        self.label_body.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_body.setText(_fromUtf8(""))
        self.label_body.setObjectName(_fromUtf8("label_body"))
        self.label_append = QtGui.QLabel(self.centralwidget)
        self.label_append.setGeometry(QtCore.QRect(110, 185, 436, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(12)
        self.label_append.setFont(font)
        self.label_append.setFrameShape(QtGui.QFrame.Panel)
        self.label_append.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_append.setText(_fromUtf8(""))
        self.label_append.setObjectName(_fromUtf8("label_append"))
        self.label_maillist = QtGui.QLabel(self.centralwidget)
        self.label_maillist.setGeometry(QtCore.QRect(150, 235, 396, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(12)
        self.label_maillist.setFont(font)
        self.label_maillist.setFrameShape(QtGui.QFrame.Panel)
        self.label_maillist.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_maillist.setText(_fromUtf8(""))
        self.label_maillist.setObjectName(_fromUtf8("label_maillist"))
        self.lineEdit_Sub = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_Sub.setGeometry(QtCore.QRect(110, 85, 491, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.lineEdit_Sub.setFont(font)
        self.lineEdit_Sub.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 120);"))
        self.lineEdit_Sub.setFrame(False)
        self.lineEdit_Sub.setObjectName(_fromUtf8("lineEdit_Sub"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 85, 48, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 135, 42, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 185, 42, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 235, 84, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lineEdit_Xls_From = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_Xls_From.setGeometry(QtCore.QRect(90, 285, 51, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(14)
        self.lineEdit_Xls_From.setFont(font)
        self.lineEdit_Xls_From.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 120);"))
        self.lineEdit_Xls_From.setFrame(False)
        self.lineEdit_Xls_From.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Xls_From.setObjectName(_fromUtf8("lineEdit_Xls_From"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 285, 41, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(150, 285, 84, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(310, 285, 84, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.lineEdit_Xls_To = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_Xls_To.setGeometry(QtCore.QRect(250, 285, 51, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(14)
        self.lineEdit_Xls_To.setFont(font)
        self.lineEdit_Xls_To.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 120);"))
        self.lineEdit_Xls_To.setText(_fromUtf8(""))
        self.lineEdit_Xls_To.setFrame(False)
        self.lineEdit_Xls_To.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Xls_To.setObjectName(_fromUtf8("lineEdit_Xls_To"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(440, 285, 31, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.lineEdit_Xls_Col = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_Xls_Col.setGeometry(QtCore.QRect(370, 285, 51, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(14)
        self.lineEdit_Xls_Col.setFont(font)
        self.lineEdit_Xls_Col.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 120);"))
        self.lineEdit_Xls_Col.setFrame(False)
        self.lineEdit_Xls_Col.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Xls_Col.setObjectName(_fromUtf8("lineEdit_Xls_Col"))
        self.listWidget = QtGui.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(30, 395, 271, 141))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 60);"))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(30, 355, 91, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.lineEdit_Sender_Name = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_Sender_Name.setGeometry(QtCore.QRect(470, 355, 131, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.lineEdit_Sender_Name.setFont(font)
        self.lineEdit_Sender_Name.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 120);"))
        self.lineEdit_Sender_Name.setFrame(False)
        self.lineEdit_Sender_Name.setObjectName(_fromUtf8("lineEdit_Sender_Name"))
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(340, 355, 121, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(340, 415, 121, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(480, 455, 131, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.spinBox_Each_Hour = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_Each_Hour.setGeometry(QtCore.QRect(340, 455, 131, 31))
        self.spinBox_Each_Hour.setMinimumSize(QtCore.QSize(71, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(16)
        self.spinBox_Each_Hour.setFont(font)
        self.spinBox_Each_Hour.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 120);"))
        self.spinBox_Each_Hour.setFrame(False)
        self.spinBox_Each_Hour.setMinimum(1)
        self.spinBox_Each_Hour.setMaximum(2000)
        self.spinBox_Each_Hour.setSingleStep(100)
        self.spinBox_Each_Hour.setProperty("value", 400)
        self.spinBox_Each_Hour.setObjectName(_fromUtf8("spinBox_Each_Hour"))
        self.spinBox_Each_Time = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_Each_Time.setGeometry(QtCore.QRect(340, 495, 131, 31))
        self.spinBox_Each_Time.setMinimumSize(QtCore.QSize(71, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(16)
        self.spinBox_Each_Time.setFont(font)
        self.spinBox_Each_Time.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 120);"))
        self.spinBox_Each_Time.setFrame(False)
        self.spinBox_Each_Time.setMinimum(1)
        self.spinBox_Each_Time.setMaximum(100)
        self.spinBox_Each_Time.setSingleStep(5)
        self.spinBox_Each_Time.setProperty("value", 40)
        self.spinBox_Each_Time.setObjectName(_fromUtf8("spinBox_Each_Time"))
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(480, 495, 131, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Malgun Gothic Semilight"))
        font.setPointSize(16)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.pushButton_OK = QtGui.QCommandLinkButton(self.centralwidget)
        self.pushButton_OK.setGeometry(QtCore.QRect(180, 550, 111, 61))
        palette = QtGui.QPalette()
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(40, 146, 216))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(40, 146, 216))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(40, 146, 216))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(40, 146, 216))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(40, 146, 216))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(40, 146, 216))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(40, 146, 216))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(40, 146, 216))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(40, 146, 216))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        self.pushButton_OK.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.pushButton_OK.setFont(font)
        self.pushButton_OK.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(40, 146, 216, 255), stop:1 rgba(255, 255, 255, 255));"))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/pic/10d.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_OK.setIcon(icon)
        self.pushButton_OK.setIconSize(QtCore.QSize(50, 40))
        self.pushButton_OK.setObjectName(_fromUtf8("pushButton_OK"))
        self.pushButton_cancel = QtGui.QCommandLinkButton(self.centralwidget)
        self.pushButton_cancel.setGeometry(QtCore.QRect(360, 550, 111, 61))
        palette = QtGui.QPalette()
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.255682, QtGui.QColor(168, 0, 255))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.255682, QtGui.QColor(168, 0, 255))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.255682, QtGui.QColor(168, 0, 255))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.255682, QtGui.QColor(168, 0, 255))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.255682, QtGui.QColor(168, 0, 255))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.255682, QtGui.QColor(168, 0, 255))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.255682, QtGui.QColor(168, 0, 255))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.255682, QtGui.QColor(168, 0, 255))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.255682, QtGui.QColor(168, 0, 255))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        self.pushButton_cancel.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.pushButton_cancel.setFont(font)
        self.pushButton_cancel.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.255682 rgba(255, 0, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.255682 rgba(168, 0, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/back/eexit.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_cancel.setIcon(icon1)
        self.pushButton_cancel.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_cancel.setObjectName(_fromUtf8("pushButton_cancel"))
        self.pushButton_account_add = QtGui.QCommandLinkButton(self.centralwidget)
        self.pushButton_account_add.setGeometry(QtCore.QRect(140, 350, 76, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI Light"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.pushButton_account_add.setFont(font)
        self.pushButton_account_add.setStyleSheet(_fromUtf8("font: 25 12pt \"Microsoft YaHei UI Light\";\n"
"color: rgb(0, 0, 255);"))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/pic/ico/Add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_account_add.setIcon(icon2)
        self.pushButton_account_add.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_account_add.setObjectName(_fromUtf8("pushButton_account_add"))
        self.pushButton_account_del = QtGui.QCommandLinkButton(self.centralwidget)
        self.pushButton_account_del.setGeometry(QtCore.QRect(220, 350, 76, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI Light"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.pushButton_account_del.setFont(font)
        self.pushButton_account_del.setStyleSheet(_fromUtf8("font: 25 12pt \"Microsoft YaHei UI Light\";\n"
"color: rgb(209, 0, 209);"))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/pic/ico/Denided.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_account_del.setIcon(icon3)
        self.pushButton_account_del.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_account_del.setObjectName(_fromUtf8("pushButton_account_del"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 5, 196, 71))
        self.label.setStyleSheet(_fromUtf8("QLabel:hover {    \n"
"    margin: 0;\n"
"}\n"
"QLabel {    \n"
"    border-image: url(:/logo/pic/mass_send2.png);\n"
"    margin: 3;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
" \n"
"}"))
        self.label.setText(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(185, 0, 101, 86))
        self.label_18.setStyleSheet(_fromUtf8("border-image: url(:/logo/pic/ico/mail512.png);"))
        self.label_18.setText(_fromUtf8(""))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.pushButton_body = QtGui.QCommandLinkButton(self.centralwidget)
        self.pushButton_body.setGeometry(QtCore.QRect(555, 130, 41, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI Light"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.pushButton_body.setFont(font)
        self.pushButton_body.setStyleSheet(_fromUtf8("font: 25 12pt \"Microsoft YaHei UI Light\";"))
        self.pushButton_body.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/back/pic/ico/Folder.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_body.setIcon(icon4)
        self.pushButton_body.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_body.setObjectName(_fromUtf8("pushButton_body"))
        self.pushButton_append = QtGui.QCommandLinkButton(self.centralwidget)
        self.pushButton_append.setGeometry(QtCore.QRect(555, 180, 36, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI Light"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.pushButton_append.setFont(font)
        self.pushButton_append.setStyleSheet(_fromUtf8("font: 25 12pt \"Microsoft YaHei UI Light\";"))
        self.pushButton_append.setText(_fromUtf8(""))
        self.pushButton_append.setIcon(icon4)
        self.pushButton_append.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_append.setObjectName(_fromUtf8("pushButton_append"))
        self.pushButton_mail_list = QtGui.QCommandLinkButton(self.centralwidget)
        self.pushButton_mail_list.setGeometry(QtCore.QRect(555, 230, 36, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI Light"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.pushButton_mail_list.setFont(font)
        self.pushButton_mail_list.setStyleSheet(_fromUtf8("font: 25 12pt \"Microsoft YaHei UI Light\";"))
        self.pushButton_mail_list.setText(_fromUtf8(""))
        self.pushButton_mail_list.setIcon(icon4)
        self.pushButton_mail_list.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_mail_list.setObjectName(_fromUtf8("pushButton_mail_list"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(575, 550, 56, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 105, 105, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 246, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 105, 105, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 246, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 105, 105, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 246, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        self.pushButton.setPalette(palette)
        self.pushButton.setStyleSheet(_fromUtf8("QPushButton:hover { \n"
"    border-image: url(:/back/pic/ico/close.ico);\n"
"}\n"
"QPushButton {    \n"
"    background-color: rgba(255, 255, 255, 0);\n"
" \n"
"}"))
        self.pushButton.setText(_fromUtf8(""))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(585, 0, 51, 51))
        self.label_2.setStyleSheet(_fromUtf8("QLabel:hover { \n"
"    \n"
"    border-image: url(:/back/pic/ico/close.ico);\n"
"}\n"
"QLabel {    \n"
"    background-color: rgba(255, 255, 255, 0);\n"
" \n"
"}"))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 636, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pushButton_cancel.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_Sub, self.lineEdit_Xls_From)
        MainWindow.setTabOrder(self.lineEdit_Xls_From, self.lineEdit_Xls_To)
        MainWindow.setTabOrder(self.lineEdit_Xls_To, self.lineEdit_Xls_Col)
        MainWindow.setTabOrder(self.lineEdit_Xls_Col, self.lineEdit_Sender_Name)
        MainWindow.setTabOrder(self.lineEdit_Sender_Name, self.spinBox_Each_Hour)
        MainWindow.setTabOrder(self.spinBox_Each_Hour, self.spinBox_Each_Time)
        MainWindow.setTabOrder(self.spinBox_Each_Time, self.listWidget)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "群发邮件", None))
        MainWindow.setToolTip(_translate("MainWindow", "欢迎使用本软件，遇到问题或有建议请联系Oliver 1026815245@qq.com", None))
        self.label_body.setToolTip(_translate("MainWindow", "请选择一个包含邮件正文的txt文本文件，如果没有则新建一个把内容复制到里面并保存", None))
        self.label_append.setToolTip(_translate("MainWindow", "请打开要发送的附件（可多选，按住Ctrl键然后选定多个）", None))
        self.label_maillist.setToolTip(_translate("MainWindow", "把收件人名单放在Excel表格的某一列", None))
        self.lineEdit_Sub.setToolTip(_translate("MainWindow", "邮件标题", None))
        self.label_4.setText(_translate("MainWindow", "标题", None))
        self.label_5.setText(_translate("MainWindow", "正文", None))
        self.label_6.setText(_translate("MainWindow", "附件", None))
        self.label_7.setText(_translate("MainWindow", "邮箱列表", None))
        self.lineEdit_Xls_From.setToolTip(_translate("MainWindow", "从1开始计数，第一张表为首张", None))
        self.lineEdit_Xls_From.setText(_translate("MainWindow", "1", None))
        self.label_8.setToolTip(_translate("MainWindow", "邮箱列表保存在Excel表格中的哪几张表，以及哪一列", None))
        self.label_8.setText(_translate("MainWindow", "从第", None))
        self.label_9.setToolTip(_translate("MainWindow", "邮箱列表保存在Excel表格中的哪几张表，以及哪一列", None))
        self.label_9.setText(_translate("MainWindow", "张表到第", None))
        self.label_10.setText(_translate("MainWindow", "张表", None))
        self.lineEdit_Xls_To.setToolTip(_translate("MainWindow", "最后一张(含)", None))
        self.label_11.setText(_translate("MainWindow", "列", None))
        self.lineEdit_Xls_Col.setToolTip(_translate("MainWindow", "保存在哪一列，A,B,C......", None))
        self.lineEdit_Xls_Col.setText(_translate("MainWindow", "C", None))
        self.listWidget.setToolTip(_translate("MainWindow", "点击\"添加\"来添加账户，多账户将自动切换发送，降低被封号的风险", None))
        self.label_12.setToolTip(_translate("MainWindow", "点击\"添加\"来添加账户，多账户将自动切换发送，降低被封号的风险", None))
        self.label_12.setText(_translate("MainWindow", "发送账户", None))
        self.lineEdit_Sender_Name.setToolTip(_translate("MainWindow", "收件人收到的邮件会看到这个名字", None))
        self.label_13.setText(_translate("MainWindow", "发件人姓名", None))
        self.label_14.setToolTip(_translate("MainWindow", "发送速度请谨慎调控，设置不当有被封号的可能", None))
        self.label_14.setText(_translate("MainWindow", "发送速度", None))
        self.label_15.setToolTip(_translate("MainWindow", "每个账号每小时的发送数量", None))
        self.label_15.setText(_translate("MainWindow", "封/账号/小时", None))
        self.spinBox_Each_Hour.setToolTip(_translate("MainWindow", "每个账号每小时的发送数量，多个账号则实际总速度更大", None))
        self.spinBox_Each_Time.setToolTip(_translate("MainWindow", "每一次发送的最大发送数量，不建议设置过小导致过于频繁得发送", None))
        self.label_16.setToolTip(_translate("MainWindow", "每一次发送的最大发送数量", None))
        self.label_16.setText(_translate("MainWindow", "封/次", None))
        self.pushButton_OK.setText(_translate("MainWindow", "开始", None))
        self.pushButton_cancel.setText(_translate("MainWindow", "退出", None))
        self.pushButton_account_add.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">添加一个账户</span></p></body></html>", None))
        self.pushButton_account_add.setText(_translate("MainWindow", "添加", None))
        self.pushButton_account_del.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">删除一个账户</span></p></body></html>", None))
        self.pushButton_account_del.setText(_translate("MainWindow", "删除", None))
        self.pushButton_body.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">请打开一个包含邮件正文的txt文件</span></p></body></html>", None))
        self.pushButton_append.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">请打开要发送的附件（可多选）</span></p></body></html>", None))
        self.pushButton_mail_list.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">请打存放开收件人Excel表格</span></p></body></html>", None))

import send1_rc
